### ISSUE TITLE
Any news in this invetigation

### ISSUE THREAD

**Issue by edumco** [singularityhub/data-container#2]
I really like your "article repository"

I think it could be used to provide static data for testing application.

What do you think about?

**Comment by vsoch** [comment]
What repository specifically?

**Comment by vsoch** [comment]
And this project is a work in progress, I do a little work here and there, singularityhub/containerdb is what I'm trying first for an in-memory database (see the readme in the Docker folder). Any particular reason you are following me? I'll post an update on twitter / blog post when I have something to share.

**Comment by edumco** [comment]
> What repository specifically?

The data container

>  Any particular reason you are following me?

I found your work cause I was studding about distrolles docker images. My area of interest is testing.

I'll keep an eye on singularityhub/containerdb :D Thanks for answering!

**Comment by vsoch** [comment]
hey @edumco actually I finished up my dummy example, the docs are here https://vsoch.github.io/cdb/ and the post is here https://vsoch.github.io/2020/data-containers/. Now it's a simple matter of deciding how an entrypoint executable might be customized for some particular dataset. Please post on the repo if you have ideas or want to work on something, thanks!
